Svarnyk user comment
fordmay/superhero-shop pull request #1
Opened 2022-05-17 09:16 UTC by svarnyk

Привіт! Перевір будь ласка чи все ОК.

2022-05-19 17:32 UTC, fordmay requested changes
загальне

2022-05-19 17:32 UTC, fordmay commented on tech/tech.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,500&display=swap" rel="stylesheet">
Прибрати підключення шрифта

2022-05-20 07:53 UTC, svarnyk reviewed
Видалив підключення шрифтів та непотрібні стилі в style.css

2022-05-20 08:30 UTC, fordmay requested changes
виправити все згідно правил курсу і БЕМ, вирішити питання з відступами, запулити

2022-05-20 08:30 UTC, fordmay commented on tech/tech.html
> +      </div>
Не відповідає правилам курсу, структура має бути типу: блок-елемент-блок

 Правила на період навчання:
- Контекст. Не думаємо про зовнішне і внутрішне.
- Блок не може бути дочірнім об’єктом іншого блоку.
- Елемент не може бути в іншому елементі
- Блок-елемент-блок

2022-05-20 08:30 UTC, fordmay commented on tech/tech.html
> +              <img class="user-comment__user-info__userPic" src="../img/UserPic.png" alt="userpic"/>
назва не відповідає БЕМ, за БЕМ треба так "user-comment__userPic", передивіться всі назви

2022-05-20 08:30 UTC, fordmay commented on tech/tech.html
> +            <div class="user-comment__user-info">
елемент не має обмеження з правої сторони, якщо додати ще контенту то він вліпиться в праву стінку (від правої стінки не буде відступу)

2022-05-20 08:30 UTC, fordmay commented on tech/tech.html
> +              <img class="user-comment__user-info__rating" src="https://placehold.jp/108x18.png" alt="rating"/>
якщо тут додати ще один блок, то він прилипне до попереднього без відстані, ліпше розділ робити не через марджін в кожному, а загальний на всі блоки через gap в user-comment__user-info

2022-05-20 14:06 UTC, svarnyk reviewed
Виправив стилі та підкоригував БЕМ

2022-05-20 15:07 UTC, svarnyk reviewed
Тепер все виправив. Наступним кроком вирішу конфлікт.

2022-05-20 15:23 UTC, svarnyk reviewed
Об'єднав свій блок з основним файлом

2022-05-20 20:02 UTC, fordmay requested changes
відредагувати блоки з картинкою, скачати останню версію змін і додати свої і запулити

2022-05-21 08:19 UTC, merged