footer
fordmay/superhero-shop pull request #7
Opened 2022-05-21 15:43 UTC by SmirnovAleksey

2022-05-22 06:42 UTC, fordmay commented
спробуйте переробити все відповідно до правил, і блок не може мати маржинів
   
Правила на період навчання:
- Контекст. Не думаємо про зовнішне і внутрішне.
- Блок не може бути дочірнім об’єктом іншого блоку.
- Елемент не може бути в іншому елементі
- Блок-елемент-блок

2022-05-22 14:11 UTC, SmirnovAleksey commented
Виправив наче

2022-05-23 16:20 UTC, fordmay requested changes
спробуйте переробити футер через флекси, і марджін і падінг використовуйте мінімально

2022-05-23 20:47 UTC, SmirnovAleksey commented
Прибрав марджини/падінги в більшості своїй, додав медіа запити на мобільні пристрої.

2022-05-24 18:14 UTC, fordmay requested changes
внесіть зміни, оновіть репозиторій до останньої зміни мого репозиторія і пульте, я буду мерджити

2022-05-24 18:14 UTC, fordmay commented on style.css
> +}
тут лишіть тільки: 
    display: flex;
    justify-content: space-between;
щоб зробити відстань між блоками

2022-05-24 18:14 UTC, fordmay commented on tech/tech.html
> +            </div>
марджін перенесіть в footer_nav__text_container

2022-05-24 18:14 UTC, fordmay commented on tech/tech.html
> +            </div>
марджін перенесіть в footer_nav__text_container

2022-05-25 14:34 UTC, fordmay requested changes
все добре, тільки я не можу вас змержити бо ви затерли чийсь кусок коду, спробуйте залити знову так щоб не було червоного)
дякую

2022-05-25 16:43 UTC, SmirnovAleksey commented
Тепер норм, здається.

2022-05-25 17:27 UTC, merged