Common-form implemented as sign up block
fordmay/superhero-shop pull request #8
Opened 2022-05-21 21:13 UTC by DmytroY

I have implemented Common-form. Please review that pull request.

2022-05-22 07:27 UTC, fordmay requested changes
додав рекомендації)

2022-05-22 07:27 UTC, fordmay commented on tech/tech.html
> +            <a href="" class="common-form__link signin-dialog__link">Sign in</a>
модифікатор зробити відповідно правил БЕМ:

Структура полного имени модификатора соответствует схеме:
имя-блока_имя-модификатора;
имя-блока__имя-элемента_имя-модификатора.

2022-05-22 07:27 UTC, fordmay commented on tech/tech.html
> +          <input class="common-form__input common-form__input_active" type="text" name="nick" placeholder="Nick name" value="Michel">
модифікатор із значенням по бем
имя-блока_имя-модификатора_значение-модификатора;
имя-блока__имя-элемента_имя-модификатора_значение-модификатора.

2022-05-22 07:27 UTC, fordmay commented on tech/tech.html
> +            <div class="common-form__spacer"></div>
не треба створювати зайві елементи для відступів, ліпше в signin-dialog додати gap: 4px;

2022-05-22 07:27 UTC, fordmay commented on tech/tech.html
> +          <div class="signin-dialog">
відповідно правил курсу не можна класти блок в блок

Правила на період навчання:
- Контекст. Не думаємо про зовнішне і внутрішне.
- Блок не може бути дочірнім об’єктом іншого блоку.
- Елемент не може бути в іншому елементі
- Блок-елемент-блок

2022-05-22 07:27 UTC, fordmay commented on tech/tech.html
> +            <input class="common-form__input names-input_left" type="text" name="first" placeholder="First name">
відповідно бем не можна класти елемент одного блока в інший блок

2022-05-22 07:27 UTC, fordmay commented on style.css
> +  width: 344px;
спробуйте використовувати в проекті max-width замість width щоб проект був не таким статичним і його можна було регулювати за розмірами

2022-05-22 07:27 UTC, fordmay commented on tech/tech.css
> -.common-form{
не видаляйте блок, в мене 2 однакових проекта задублювалось, змініть просто в своєму проекті назву класу на .common-form2, і не буде конфлікту

2022-05-23 15:40 UTC, DmytroY commented on tech/tech.html
> +            <a href="" class="common-form__link signin-dialog__link">Sign in</a>
Ок. **signin-dialog__link**   замінюю на   **common-form__link_under**

2022-05-23 15:40 UTC, DmytroY commented on tech/tech.html
> +          <input class="common-form__input common-form__input_active" type="text" name="nick" placeholder="Nick name" value="Michel">
Не зрозумів. Як на мене **common-form__input_active**  це віідповідає  Б__Е_М

2022-05-23 15:40 UTC, DmytroY commented on tech/tech.html
> +            <div class="common-form__spacer"></div>
Використання спейсерів є однією з рекомендованих практик для зручного контролю відстаней у флекс. Я хотів би лишити як є.

2022-05-23 15:41 UTC, DmytroY commented on tech/tech.html
> +          <div class="signin-dialog">
:) Як раз подумав коли писав це - чи робити за правилами курсу чи за загальними правилами БЕМ :). Звісно я можу загорнути в конструкцію Блок-елемент-блок-елемент, але на мій погляд це лише погіршить читаємість коду. Прошу прийняти як є, але якщо будете наполягати - зрозумію і перероблю.

2022-05-23 15:41 UTC, DmytroY commented on tech/tech.html
> +            <input class="common-form__input names-input_left" type="text" name="first" placeholder="First name">
коментарій аналогічно тому що вище.

2022-05-23 15:41 UTC, DmytroY commented on style.css
> +  width: 344px;
Слушно. Дякую.

2022-05-23 15:41 UTC, DmytroY commented on tech/tech.css
> -.common-form{
Ок. Повертаю як було. Перейменовую свій кусок на **common-form2**.

2022-05-23 16:29 UTC, fordmay commented
за бем то мій косяк) щось я після іншої перевірки натупив, перезалийте проект щоб не було конфліктів і я замержу.

2022-05-23 16:33 UTC, fordmay commented on tech/tech.html
> +            <div class="common-form__spacer"></div>
лишайте) 
а в чому суть спейсерів? як на мене вони створюють додатковий код, і роблять сайт більш статичним, 
і якщо замінити їх аналогом типу gap то можна додавати елементи і вони автоматично будуть ставати на потрібній відстані

2022-05-23 18:28 UTC, DmytroY commented
Перезалив. Конфліктів немає

2022-05-23 18:34 UTC, merged